platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!
project 'DouYuTV'

target 'DouYuTV' do
    pod 'Alamofire', '~> 4.0'
    pod 'SnapKit', '~> 3.0.2'
    pod 'Kingfisher'
    pod 'ObjectMapper', '~> 2.2.1' 
    pod 'MBProgressHUD', '~> 1.0.0'
    pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift3' 
    pod 'RealmSwift'
end 
