platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!
project 'DouYuTV'

target 'DouYuTV' do
    pod 'Alamofire'
    pod 'SnapKit'
    pod 'ObjectMapper' 
    pod 'MBProgressHUD', '~> 1.0.0'
    pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift3' 
    pod 'RealmSwift'
    pod 'Kingfisher'
    pod 'SwiftKeychainWrapper'
    pod 'UMengUShare/Social/Sina'
    pod 'UMengUShare/Social/WeChat'
    pod 'UMengUShare/Social/QQ'
    pod 'UMengUShare/UI'
    pod 'BarrageRenderer'
   #pod 'GPUImage' 由于LFLiveKit里面已经集成了GPUImage
    pod 'LFLiveKit'
end 
